[tool.poetry]
name = "nade"
version = "0.1.0"
description = "Natural affect detection allows to infer basic emotions from social media messages"
authors = ["Christian Hotz-Behofsits <chris.hotz.behofsits@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
fasttext = "^0.9.0"
numpy = "^1.19"
lightgbm = "^3.2"
pyarrow = "^6.0.1"
regex = "^2021.11.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
